name: test
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install iverilog
        shell: bash
        run: sudo apt-get update && sudo apt-get install -y iverilog

      # Setup Python and cocotb
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python packages
        shell: bash
        run: pip install -r test/requirements.txt

      - name: Run tests (non-blocking)
        run: |
          cd test
          make clean
          make
          echo "====== RESULTS.XML CONTENT ======"
          cat results.xml || echo "⚠️ results.xml not found!"
          echo "================================"
          if [ -f results.xml ] && grep -q "<failure" results.xml; then
            echo "❌ Test failed – but workflow will continue (debug mode)."
            exit 0
          else
            echo "✅ All tests passed."
          fi

      - name: Test Summary
        uses: test-summary/action@v2.3
        with:
          paths: "test/results.xml"
        if: always()

      - name: Upload VCD + results
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-vcd
          path: |
            test/tb.vcd
            test/results.xml
